package com.raian.cricketeoapp.models

import com.raian.cricketeoapp.models.league.League
import kotlinx.parcelize.RawValue

data class MatchResult(
    val balls: List<Ball>?,
    val batting: List<Batting>?,
    val bowling: List<Bowling>?,
    //val draw_noresult: Any?,
    val elected: String?,
    val first_umpire_id: Int?,
    val follow_on: Boolean?,
    val id: Int?,
   // val last_period: Any?,
    val league_id: Int?,
    val league: League?,
    val live: Boolean?,
    val localteam: Localteam?,
    //val localteam_dl_data: LocalteamDlDataX?,
    val localteam_id: Int?,
    val man_of_match_id: Int?,
    //val man_of_series_id: Any?,
    val manofmatch: Manofmatch?,
    val note: String?,
    val referee_id: Int?,
    val resource: String?,
    val round: String?,
   // val rpc_overs: Any?,
   // val rpc_target: Any?,
    //val runs: List<Run>,
    val scoreboards: List<Scoreboard>?,
    val season_id: Int?,
    val second_umpire_id: Int?,
    val stage_id: Int?,
    val starting_at: String?,
    val status: String?,
    val super_over: Boolean?,
    val toss_won_team_id: Int?,
    //val total_overs_played: Any?,
    val lineup:@RawValue List<Lineup>?,
    val tv_umpire_id: Int?,
    val type: String?,
    val venue: Venue?,
    val venue_id: Int?,
    val visitorteam: Visitorteam?,
    //val visitorteam_dl_data: VisitorteamDlDataX?,
    val visitorteam_id: Int?,
   // val weather_report: List<Any>?,
    val winner_team_id: Int?
)